font_family      JetBrainsMono Nerd Font Propo Regular
bold_font        JetBrainsMono Nerd Font Propo Bold
italic_font      JetBrainsMono Nerd Font Propo Italic
bold_italic_font JetBrainsMono Nerd Font Propo Bold Italic
font_size        14.0

shell tmux

hide_window_decorations yes
window_padding_width    10
background_opacity      0.9
background_blur         0
confirm_os_window_close 0

scrollback_lines 10000
touch_scroll_multiplier 3.0

cursor_trail 10
cursor_trail_decay 0.1 0.2
cursor_trail_start_threshold 0

foreground #a9b1d6
background #1a1b26

color0 #32344a
color8 #444b6a

color1 #f7768e
color9 #ff7a93

color2 #9ece6a
color10 #b9f27c

color3 #e0af68
color11 #ff9e64

color4 #7aa2f7
color12 #7da6ff

color5 #ad8ee6
color13 #bb9af7

color6 #449dab
color14 #0db9d7

color7 #787c99
color15 #acb0d0
