set -g prefix `
bind ` send-prefix
set -g default-terminal "screen-256color"
set -ga terminal-overrides ',xterm-256color:Tc'
set-option -g focus-events on

# evil
set -g mouse on

set -gq allow-passthrough on
set -g visual-activity off

set -g base-index 1
set -sg escape-time 0

# vim mode yay
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Use vim-style copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# status bar
set-option -g status-position top
set -g status-right '#[fg=color249]#(date +"%H:%M %d-%m-%Y")#[default]'

# colors
set -g status-style "bg=color233,fg=color249"
set -g mode-style "fg=color0,bg=color11"
set -g pane-active-border-style 'fg=color238'
set -g pane-border-style 'fg=color236'

# keymaps
bind r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"
bind d "detach"
bind N "new-session"
bind n command-prompt -p "New session name:" "new-session -s '%%'"
bind J display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind p command-prompt -p "move pane to:" "join-pane -t :'%%'"
bind o break-pane
bind -n M-C-right swap-window -t -1\; select-window -t -1
bind -n M-C-left swap-window -t +1\; select-window -t +1
# bind -n M-h swap-pane -t -1\; select-pane -t -1
# bind -n M-l swap-pane -t +1\; select-pane -t +1
bind -n M-tab switch-client -n
bind -n M-btab switch-client -p
bind -r tab next-window
bind -r btab previous-window

bind '\' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"

bind C new-window -c "#{pane_current_path}"

### plugins

run-shell ~/.config/tmux/plugins/tmux-matryoshka/matryoshka.tmux
set -g @matryoshka_inactive_status_style_strategy 'assignment'
set -g @matryoshka_inactive_status_style 'bg=colour223,fg=colour239'

run-shell ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
