#!/bin/bash

BASH_CONFIG_DIR="$HOME/.config/bash"

for file in "$BASH_CONFIG_DIR"/*.sh; do
  [ -f "$file" ] && source "$file"
done

for file in "$BASH_CONFIG_DIR"/tools/*.sh; do
  [ -f "$file" ] && source "$file"
done
