Section "InputClass"
    Identifier "Touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"

    Option "AccelProfile" "flat"
    Option "AccelSpeed" "-0.25"

    Option "NaturalScrolling" "true"

    Option "Tapping" "on"
EndSection
